//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nusantara.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailSchedule()
        {
            this.DetailScores = new HashSet<DetailScore>();
        }
    
        public int DetailId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string SubjectId { get; set; }
        public string TeacherId { get; set; }
        public string Day { get; set; }
        public Nullable<int> ShiftId { get; set; }
    
        public virtual HeaderSchedule HeaderSchedule { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailScore> DetailScores { get; set; }
    }
}
