//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nusantara.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderSchedule()
        {
            this.DetailSchedules = new HashSet<DetailSchedule>();
        }
    
        public int ScheduleId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> Finalize { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailSchedule> DetailSchedules { get; set; }
    }
}
