//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nusantara.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string SubjectName { get; set; }
        public string TeacherName { get; set; }
        public string ClassName { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string SubjectId { get; set; }
        public string TeacherId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public int DetailId { get; set; }
    }
}
